services:
  app:
    build: .
    container_name: mezzio_project
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - .:/var/www/html
